How to Build Tensors with TensorFlow

In [1]:
import tensorflow as tf

Let’s first create a scalar using tf.constant. We use tf.constant to create a new constant value. We can also use tf.variable to create a variable value. We will then print the value and also check the dimension of the scalar using the ndim property. Its dimension will be zero because it is a single value.

In [2]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


Now let’s create a vector and print its dimensions. You can see that the dimension is 1.

In [3]:
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


Now let’s try creating a matrix and printing its dimensions.

In [4]:
matrix = tf.constant([
    [10, 11],
    [12, 13]
])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)
2


Let’s create the same matrix again with float16 as the data type.

In [5]:
tensor_1 = tf.constant([
    [
        [1, 2, 3]
    ],
    [
        [4, 5, 6]
    ],
    [
        [7, 8, 9]
    ]
], dtype='float32')
print(tensor_1)

tf.Tensor(
[[[1. 2. 3.]]

 [[4. 5. 6.]]

 [[7. 8. 9.]]], shape=(3, 1, 3), dtype=float32)


We will use tf.Variable to create a variable tensor. The difference between the constant tensor and variable tensor is that you can change the data in a variable tensor, but you can’t change the values in a constant tensor. Let’s create a variable tensor and print the dimensions.

In [6]:
var_tensor = tf.Variable([
    [
        [1, 2, 3]
    ],
    [
        [4, 5, 6]
    ],
    [
        [7, 8, 9]
    ]
])
print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 1, 3) dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])>


How to Generate and Load Tensors

Let’s create two arrays of random tensors. We will first set a seed and generate the random values using that seed.

In [7]:
seed = tf.random.Generator.from_seed(42)

Now we will create a normal and uniform distribution with the shape of 3 by 2.

In [8]:
normal_tensor = seed.normal(shape=(3, 2))
print(normal_tensor)
uniform_tensor = seed.uniform(shape=(3, 2))
print(uniform_tensor)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7647915  0.03845465]
 [0.8506975  0.20781887]
 [0.711869   0.8843919 ]], shape=(3, 2), dtype=float32)


Next, we will create a tensor with zeros and ones. In TensorFlow, tensors filled with zeros or ones are often used as a starting point for creating other tensors. They can also be placeholders for inputs in a computational graph.

In [9]:
zeros = tf.zeros(shape=(3, 2))
print(zeros)
ones = tf.ones(shape=(3, 2))
print(ones)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Let’s import NumPy and create a NumPy array using NumPy’s arrange function.

In [11]:
import numpy as np
numpy_arr = np.arange(1, 25,dtype=np.int32)
print(numpy_arr,"Array")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] Array


In [12]:
numpy_tensor = tf.constant(numpy_arr,shape=[2,3,4])
print(numpy_tensor)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


Basic Operations using Tensorflow


We have learned how tensors are created in TensorFlow. Now let’s look at some basic operations using tensors.

We will start by getting some information on our tensors. Let’s create a 4D tensor with 0 values with the shape 2x3x4x5.

In [13]:
rank4_tensor = tf.zeros([2, 3, 4, 5])
print(rank4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [14]:
basic_tensor = tf.constant([[10, 11], [12, 13]])
print(basic_tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


Let’s try some simple operations. We can add, subtract, multiply, and divide every value in a tensor using the basic operators.

In [15]:
print(basic_tensor + 10)
print(basic_tensor - 10)
print(basic_tensor * 10)
print(basic_tensor / 10)

tf.Tensor(
[[20 21]
 [22 23]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 110]
 [120 130]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  1.1]
 [1.2 1.3]], shape=(2, 2), dtype=float64)


In [16]:
tensor_011 = tf.constant([[2, 2], [4, 4]])
tensor_012 = tf.constant([[2, 3],[4,5]])

In [17]:
print(tf.matmul(tensor_011, tensor_012))

tf.Tensor(
[[12 16]
 [24 32]], shape=(2, 2), dtype=int32)
